### PR TITLE
file adaptor w/ new interface

### LINKED ISSUE #252: Crash when writing to file:
### Relevant config.yaml and application.js:

nodes:
  mongodbenron:
    type: mongodb
    uri: mongodb://example:example@aws-us-east-1-portal.7.dblayer.com:10764,aws-us-east-1-portal.10.dblayer.com:10361/enron1
    ssl: true
    namespace: enron1.enron
  dumphere:
    type: file
    uri: file://./dump.json

### System info:

- Transporter version :0.1.2
- OS : macOS Sierra
- DB version(s) : MongoDB 3.2.6

### Reproducible Steps:

Run configuration

### What did you expect to happened?

For database collection to be copied to the file.

### What actually happened?

~/D/transporter ❯❯❯ ./transporter-0.1.2-darwin-amd64 run application.js       ⏎
INFO[0001] adaptor Starting...                           path=mongodbenron
INFO[0001] starting Read func                            db=enron1
INFO[0001] collection count                              db=enron1 num_collections=3
INFO[0001] sending for iteration...                      collection=enron db=enron1
INFO[0001] skipping iteration...                         collection=experimental db=enron1
INFO[0001] skipping iteration...                         collection=system.indexes db=enron1
INFO[0001] done iterating collections                    db=enron1
INFO[0001] iterating...                                  collection=enron
panic: open ./dump.json: too many open files

goroutine 82 [running]:
panic(0xa2a700, 0xc420399890)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
github.com/compose/transporter/pkg/message/adaptor/file.Adaptor.MustUseFile(0x0, 0x0, 0x0, 0xc420620be0, 0x12, 0x0, 0x0)
	/Users/JP/gocode/src/github.com/compose/transporter/pkg/message/adaptor/file/file.go:75 +0xb0
github.com/compose/transporter/pkg/adaptor/file.(*File).dumpMessage(0xc420195650, 0x11cb620, 0xc42037ac90, 0xc420919ac7, 0x5, 0x0, 0x0)
	/Users/JP/gocode/src/github.com/compose/transporter/pkg/adaptor/file/file.go:122 +0xbb
github.com/compose/transporter/pkg/adaptor/file.(*File).(github.com/compose/transporter/pkg/adaptor/file.dumpMessage)-fm(0x11cb620, 0xc42037ac90, 0xc4200aae60, 0xc42037a801, 0x0, 0x0)
	/Users/JP/gocode/src/github.com/compose/transporter/pkg/adaptor/file/file.go:85 +0x3e
github.com/compose/transporter/pkg/pipe.(*Pipe).Listen(0xc4205a8880, 0xc4203d5e38, 0xc4200aae60, 0x0, 0x0)
	/Users/JP/gocode/src/github.com/compose/transporter/pkg/pipe/pipe.go:106 +0x2b7
github.com/compose/transporter/pkg/adaptor/file.(*File).Listen(0xc420195650, 0x0, 0x0)
	/Users/JP/gocode/src/github.com/compose/transporter/pkg/adaptor/file/file.go:85 +0xf6
github.com/compose/transporter/pkg/transporter.(*Node).Start(0xc420202c60, 0x0, 0x0)
	/Users/JP/gocode/src/github.com/compose/transporter/pkg/transporter/node.go:165 +0xaa
github.com/compose/transporter/pkg/transporter.(*Node).Start.func1(0xc420202c60)
	/Users/JP/gocode/src/github.com/compose/transporter/pkg/transporter/node.go:157 +0x2b
created by github.com/compose/transporter/pkg/transporter.(*Node).Start
	/Users/JP/gocode/src/github.com/compose/transporter/pkg/transporter/node.go:158 +0x64

### PR DESCRIPTION
**Pull request by trinchan**
TODO:

- [x] Tests? The pipeline test does use the file adaptor, but could use unit tests as well 

fixes #252

### CODE REVIEW

**Comment by jipperinbham** [comment]
some test coverage would be good but the primary purpose of the file adaptor has always been to easily test things so they are not super critical.

File: pkg/adaptor/mongodb/adaptor_test.go [hunk 1]
```diff
@@ -11,7 +11,6 @@ import (
 )
 
 var (
-	defaultTestURI    = DefaultURI
```
Comment (jipperinbham) [inline pkg/adaptor/mongodb/adaptor_test.go]: cleanup

File: pkg/adaptor/mongodb/client_test.go [hunk 2]
```diff
@@ -356,7 +356,7 @@ func TestConnect(t *testing.T) {
 		if err != ct.expectedErr {
 			t.Fatalf("[%s] unexpected Connect error, expected %+v, got %+v\n", ct.name, ct.expectedErr, err)
 		}
-		if err != nil {
+		if err == nil {
```
Comment (jipperinbham) [inline pkg/adaptor/mongodb/client_test.go]: this was just wrong :man_facepalming:

File: pkg/adaptor/mongodb/writer_test.go [hunk 3]
```diff
@@ -84,7 +84,7 @@ func TestInsert(t *testing.T) {
 	w := newWriter(writerTestData.DB)
 	for _, it := range inserttests {
 		for _, data := range it.data {
-			msg := message.From(ops.Insert, fmt.Sprintf("%s.%s", writerTestData.DB, it.collection), data)
+			msg := message.From(ops.Insert, it.collection, data)
```
Comment (jipperinbham) [inline pkg/adaptor/mongodb/writer_test.go]: use new namespace style

File: pkg/adaptor/mongodb/writer_test.go [hunk 4]
```diff
@@ -132,16 +132,15 @@ func TestUpdate(t *testing.T) {
 	}
 	w := newWriter(writerTestData.DB)
 	for _, ut := range updatetests {
-		ns := fmt.Sprintf("%s.%s", writerTestData.DB, ut.collection)
```
Comment (jipperinbham) [inline pkg/adaptor/mongodb/writer_test.go]: use new namespace style here as well

File: pkg/adaptor/rethinkdb/adaptor_test.go [hunk 5]
```diff
@@ -10,7 +10,6 @@ import (
 )
 
 var (
-	defaultTestURI    = DefaultURI
```
Comment (jipperinbham) [inline pkg/adaptor/rethinkdb/adaptor_test.go]: cleanup

File: pkg/adaptor/rethinkdb/client_test.go [hunk 6]
```diff
@@ -302,7 +302,7 @@ func TestConnect(t *testing.T) {
 		if err != ct.expectedErr {
 			t.Fatalf("[%s] unexpected Connect error, expected %+v, got %+v\n", ct.name, ct.expectedErr, err)
 		}
-		if err != nil {
+		if err == nil {
```
Comment (jipperinbham) [inline pkg/adaptor/rethinkdb/client_test.go]: fixing logic
